"""Type stubs for the Rust engine bindings."""

from collections.abc import Mapping, Sequence
from typing import Any

__version__: str
PRODUCTS: list[str]
ITEMS: list[str]
CROPS: list[str]
ANIMALS: list[str]
SHOPS: list[str]

class Random:
    """A CPython-compatible ``random.Random`` stream."""

    def __init__(self, seed: int) -> None: ...
    @staticmethod
    def for_day(seed: int, day: int) -> Random: ...
    def random(self) -> float: ...
    def getrandbits(self, k: int) -> int: ...
    def randbelow(self, n: int) -> int: ...
    def choice(self, seq: Sequence[Any]) -> Any: ...
    def __copy__(self) -> Random: ...

class Engine:
    """One Kaggriculture episode."""

    def __init__(
        self,
        configuration: Mapping[str, Any] | None = None,
        *,
        seed: int | None = None,
        players: int = 2,
    ) -> None: ...
    @staticmethod
    def from_state(
        state: Mapping[str, Any],
        configuration: Mapping[str, Any] | None = None,
        *,
        seed: int | None = None,
    ) -> Engine: ...
    seed: int
    @property
    def players(self) -> int: ...
    @property
    def configuration(self) -> dict[str, Any]: ...
    @property
    def step_count(self) -> int: ...
    @property
    def day(self) -> int: ...
    @property
    def hour(self) -> int: ...
    @property
    def done(self) -> bool: ...
    @property
    def rewards(self) -> list[float]: ...
    @property
    def money(self) -> list[float]: ...
    def reset(self) -> None: ...
    def step(self, actions: Sequence[Any] | None) -> None: ...
    def observation(self, player: int) -> dict[str, Any]: ...
    def observations(self) -> list[dict[str, Any]]: ...
    def state(self) -> dict[str, Any]: ...
    def load_state(self, state: Mapping[str, Any]) -> None: ...
    def render(self) -> str: ...
    def copy(self) -> Engine: ...
    def __copy__(self) -> Engine: ...
    def __deepcopy__(self, memo: Any) -> Engine: ...

def market_price(item: str, inventory: int) -> int: ...
def pass_agent(engine: Engine, player: int) -> dict[str, Any]: ...
def starter_agent(engine: Engine, player: int) -> dict[str, Any]: ...
def random_agent(engine: Engine, player: int, rng: Random) -> dict[str, Any]: ...
