"""Freeze a searched route into a standalone, submittable policy module.

A route that passed the held-out gate (``holdout.py``) is a 720-entry Python
list; nothing else about it is agent-shaped. This turns that list into a file
Kaggle can load directly -- ``main.py``-compatible, no ``kaggriculture``
import, no torch -- by embedding the route as zlib-compressed, base85-encoded
JSON, the same convention ``boatlee_v14_policy.py`` uses for its own
``_ACTIONS`` tape. Decoding at import costs one zlib call on a payload smaller
than that file's, not a per-turn cost.

The generated module's replay indexing is copied from
``kaggriculture.search.arena._replay`` on purpose, offset and all -- see that
module's docstring, reproduced in the generated file's own, for why the
offset is ``+1`` and not ``0``.
"""

import argparse
import base64
import json
import logging
import zlib
from pathlib import Path

from kaggriculture.search.route import Route, load

LOGGER = logging.getLogger(__name__)

_TEMPLATE = '''"""Policy: replay the searched, held-out-gated route embedded below.

Generated by ``kaggriculture.search.scripts.embed_route`` from {source!r}; do
not hand-edit this file -- regenerate it from the route instead. Loading it
requires nothing beyond the standard library, so it runs unchanged wherever
Kaggle's own loader runs it: that loader ``exec``s this file with an empty
globals dict and takes the *last* callable defined in the resulting
namespace, so ``agent`` is deliberately the final definition below, and
nothing here may reference ``__file__``, which that exec does not provide.

**The +1 offset is the load-bearing part of this file.** It is copied from
``kaggriculture.search.arena._replay``, which this module must keep matching
exactly, because that offset is what makes the route below the same route
that passed the gate rather than a shifted one turn early or late.

``environment.steps[t]["action"]`` is the action an agent chose while looking
at the observation whose own ``step`` field reads ``t - 1``: it lands in the
recorded tape at the index of the state it *produced*, one ahead of the state
it was *chosen from*. The route below was harvested with that same indexing
(``kaggriculture.search.route.from_episode`` reads straight off
``episode["steps"]``), so the action to submit when the engine hands this
agent an observation at step ``k`` is ``_ROUTE[k + 1]``, not ``_ROUTE[k]``.
That off-by-one was found by a fidelity test refusing to pass, and it is
trivial to reintroduce: ``_ROUTE[step]`` in place of ``_ROUTE[step + 1]``
type-checks, runs a full episode without raising, and just plays the wrong
action on every single turn.

There is deliberately no fallback for a step past the end of ``_ROUTE``
either. A full season is exactly {steps} turns, so an observation asking for
one more than that means the route does not describe this season, and
indexing past its end should raise ``IndexError`` rather than silently pad
the rest of the game with PASS.
"""

import base64
import json
import zlib
from typing import Any

_ROUTE: list[dict[str, Any]] = json.loads(
    zlib.decompress(
        base64.b85decode(
            "{blob}"
        )
    ).decode("utf-8")
)


def agent(
    observation: dict[str, Any], configuration: dict[str, Any] | None = None
) -> dict[str, Any]:
    """Return the route's recorded action for this turn.

    Args:
        observation: The engine's observation; only ``observation["step"]``
            is read.
        configuration: Unused; accepted because the engine calls every agent
            with both positional arguments.

    Returns:
        The action recorded at ``observation["step"] + 1`` -- see this
        module's docstring for why the offset is ``+1``.
    """
    return _ROUTE[int(observation["step"]) + 1]
'''


def embed(route: Route, source: str) -> str:
    """Return the generated module's source for ``route``.

    Args:
        route: The route to embed, already normalised by ``route.load``.
        source: Where ``route`` came from, recorded in the generated module's
            docstring for provenance only -- nothing at runtime reads it.

    Returns:
        The complete Python source of the standalone policy module.
    """
    blob = base64.b85encode(zlib.compress(json.dumps(route).encode("utf-8"))).decode(
        "ascii"
    )
    return _TEMPLATE.format(source=source, steps=len(route), blob=blob)


def main() -> None:
    """Generate a standalone policy module from a route file, from the CLI."""
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("route", type=Path, help="route (JSON) to embed")
    parser.add_argument("output", type=Path, help="path to write the policy module to")
    arguments = parser.parse_args()

    route = load(arguments.route)
    written = arguments.output.write_text(embed(route, arguments.route.name))
    LOGGER.info("wrote %s (%d bytes)", arguments.output, written)


if __name__ == "__main__":
    main()
